ProductsCatalog.Website/ViewModels/SlideshowViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductsCatalog.Website.ViewModels
{
    public class SlideshowViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string SubTitle { get; set; }

        public string Photo { get; set; }

        public string Description { get; set; }

        public string Heading
        {
            get
            {
                return (Id != 0) ? "Update Category" : "Add New Category";
            }
        }

        public string Action
        {
            get
            {
                return (Id != 0) ? "Update" : "Create";
            }
        }
    }
}

ProductsCatalog.Website/Controllers/SlideshowController.cs
using AutoMapper;
using ProductsCatalog.Business.DTOs;
using ProductsCatalog.Business.IService;
using ProductsCatalog.Website.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductsCatalog.Website.Controllers
{
    public class SlideshowController : Controller
    {
        private readonly ISlideshowService _slideshowService;

        public SlideshowController(ISlideshowService slideshowService)
        {
            _slideshowService = slideshowService;
        }

        public ActionResult Index(int? categoryId)
        {
            var result = Mapper.Map<List<SlideshowViewModel>>(_slideshowService.GetAll());
            return View(result);
        }

        public ActionResult Create()
        {
            return View("SlideshowForm", new SlideshowViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SlideshowViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("SlideshowForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _slideshowService.Creare(Mapper.Map<SlideshowDto>(viewModel));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            var slideshowViewModel = Mapper.Map<SlideshowViewModel>(_slideshowService.GetById(Id));
            return View("SlideshowForm", slideshowViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(SlideshowViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("SlideshowForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _slideshowService.Update(Mapper.Map<SlideshowDto>(viewModel));
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int Id)
        {
            _slideshowService.Delete(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private string UploadPhoto(HttpPostedFileBase file)
        {
            string fileName = "";
            fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid() +
            Path.GetExtension(file.FileName);
            file.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
            return fileName;
        }
    }
}

ProductsCatalog.Website/Views/Slideshow/Index.cshtml
@model IEnumerable<ProductsCatalog.Website.ViewModels.SlideshowViewModel>

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Slideshow</h2>

<button type="button" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("Create", "Slideshow") + "'");">Add new slideshow</button>

<table class="table">
  <thead>
    <tr>
      <th style="text-align: center">Photo</th>
      <th>Title</th>
      <th>SubTitle</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var slide in Model)
    {
      <tr id="Row_@slide.Id">
        <td style="text-align: center"><img width="150" src="/Uploads/@slide.Photo" /></td>
        <td>@slide.Title</td>
        <td>@slide.SubTitle</td>
        <td>
          <a type="button" class="btn btn-primary" href="@Url.Action("Update","Slideshow",new { id=slide.Id})">
            Edit
          </a>
          <button type="button" class="btn btn-danger" data-toggle="modal" data-slide-Id="@slide.Id" data-target="#deleteModal">Delete</button>
        </td>
      </tr>
    }
  </tbody>
</table>

<!-- Modaml -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete</h5>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this slide?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-primary" id="confirmDelete">Yes</button>
      </div>
    </div>
  </div>
</div>


@section scripts{
  <script type="text/javascript">

    var slideId;
    $('#deleteModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget)
      slideId = button.data('slide-Id')
    });

    $("#confirmDelete").click(function () {
      $.ajax({
        type: "Get",
        url: '/Slideshow/Delete/' + slideId,
        success: function (result) {
          if (result) {
            $('#deleteModal').modal('hide');
            $('#Row_' + slideId).remove();
          }
          else {
            console.log("There is something wrong");
          }
        }
      });
    });
  </script>

}

ProductsCatalog.Website/Views/Slideshow/SlideshowForm.cshtml
@model ProductsCatalog.Website.ViewModels.SlideshowViewModel

@{
  ViewBag.Title = @Model.Heading;
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Heading</h2>

@using (@Html.BeginForm(Model.Action, "Slideshow", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

  @Html.AntiForgeryToken()

  @Html.HiddenFor(m => m.Id)

  <div class="form-group">
    @Html.LabelFor(m => m.Title)
    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", autofocus = "autofocus" })
    @Html.ValidationMessageFor(m => m.Title)
  </div>

  <div class="form-group">
    @Html.LabelFor(m => m.SubTitle)
    @Html.TextBoxFor(m => m.SubTitle, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.SubTitle)
  </div>

  <div class="form-group">
    @Html.LabelFor(m => m.Photo)

    @if (@Model.Photo != null && @Model.Photo != "")
    {
      <input type="file" name="file" value="">
      @Html.HiddenFor(model => model.Photo)
      <img src="~/Uploads/@Model.Photo" id="myImg" width="200" />
    }
    else
    {
      <input type="file" name="file" value="" />
      <img src="~/Uploads/@Model.Photo" id="myImg" width="200" hidden />
    }
  </div>
  <div class="form-group">
    @Html.LabelFor(m => m.Description)
    @Html.TextAreaFor(x => x.Description, 5, 30, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Description)
  </div>

  <button type="submit" class="btn btn-primary btn-lg">Save</button>
  <button type="button" class="btn btn-danger btn-lg" onclick="@("window.location.href='" + @Url.Action("Index", "Sideshow") + "'");">Cancel</button>

}


@section scripts{
  <script type="text/javascript">
    $(function () {
      $(":file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = imageIsLoaded;
          reader.readAsDataURL(this.files[0]);
          $('#myImg').show();
        }
      });
    });

    function imageIsLoaded(e) {
      $('#myImg').attr('src', e.target.result);
      $('#myImg').show();
    };

  </script>
}