ProductsCatalog.Website/ViewModels/SlideshowViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductsCatalog.Website.ViewModels
{
    public class SlideshowViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string SubTitle { get; set; }

        public string Photo { get; set; }

        public string Description { get; set; }

        public string Heading
        {
            get
            {
                return (Id != 0) ? "Update Category" : "Add New Category";
            }
        }

        public string Action
        {
            get
            {
                return (Id != 0) ? "Update" : "Create";
            }
        }
    }
}

ProductsCatalog.Website/Controllers/CategoryController.cs
using AutoMapper;
using ProductsCatalog.Business.DTOs;
using ProductsCatalog.Business.IService;
using ProductsCatalog.Website.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductsCatalog.Website.Controllers
{

    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        // GET: Category
        public ActionResult Index()
        {
            var result = Mapper.Map<List<CategoryViewModel>>(_categoryService.GetAll());
            return View(result);
        }


        public ActionResult Create()
        {
            return View("CategoryForm", new CategoryViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("CategoryForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _categoryService.Creare(Mapper.Map<CategoryDto>(viewModel));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            var categoryViewModel = Mapper.Map<CategoryViewModel>(_categoryService.GetById(Id));
            return View("CategoryForm", categoryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CategoryViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("CategoryForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _categoryService.Update(Mapper.Map<CategoryDto>(viewModel));
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int Id)
        {
            _categoryService.Delete(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private string UploadPhoto(HttpPostedFileBase file)
        {
            string fileName = "";
            fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid() +
            Path.GetExtension(file.FileName);
            file.SaveAs(Path.Combine(Server.MapPath("~/Uploads/Category"), fileName));
            return fileName;
        }

    }
}

ProductsCatalog.Website/Controllers/ProductController.cs
using AutoMapper;
using ProductsCatalog.Business.DTOs;
using ProductsCatalog.Business.IService;
using ProductsCatalog.Website.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductsCatalog.Website.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public ActionResult Index(int? categoryId)
        {
            var result = Mapper.Map<List<ProductViewModel>>(_productService.GetAll(categoryId));
            return View(result);
        }

        public ActionResult Create()
        {
            var product = new ProductViewModel
            {
                CategoriesList = Mapper.Map<List<CategoryViewModel>>(_categoryService.GetAll())
            };
            return View("ProductForm", product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                viewModel.CategoriesList = Mapper.Map<List<CategoryViewModel>>(_categoryService.GetAll());
                return View("ProductForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _productService.Creare(Mapper.Map<ProductDto>(viewModel));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            var productViewModel = Mapper.Map<ProductViewModel>(_productService.GetById(Id));
            productViewModel.CategoriesList = Mapper.Map<List<CategoryViewModel>>(_categoryService.GetAll());
            return View("ProductForm", productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ProductViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                viewModel.CategoriesList = Mapper.Map<List<CategoryViewModel>>(_categoryService.GetAll());
                return View("ProductForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _productService.Update(Mapper.Map<ProductDto>(viewModel));
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int Id)
        {
            _productService.Delete(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private string UploadPhoto(HttpPostedFileBase file)
        {
            string fileName = "";
            fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid() +
            Path.GetExtension(file.FileName);
            file.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
            return fileName;
        }
    }
}

ProductsCatalog.Website/Controllers/SlideshowController.cs
using AutoMapper;
using ProductsCatalog.Business.DTOs;
using ProductsCatalog.Business.IService;
using ProductsCatalog.Website.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductsCatalog.Website.Controllers
{
    public class SlideshowController : Controller
    {
        private readonly ISlideshowService _slideshowService;

        public SlideshowController(ISlideshowService slideshowService)
        {
            _slideshowService = slideshowService;
        }

        public ActionResult Index(int? categoryId)
        {
            var result = Mapper.Map<List<SlideshowViewModel>>(_slideshowService.GetAll());
            return View(result);
        }

        public ActionResult Create()
        {
            return View("SlideshowForm", new SlideshowViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SlideshowViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("SlideshowForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _slideshowService.Creare(Mapper.Map<SlideshowDto>(viewModel));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int Id)
        {
            var slideshowViewModel = Mapper.Map<SlideshowViewModel>(_slideshowService.GetById(Id));
            return View("SlideshowForm", slideshowViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(SlideshowViewModel viewModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("SlideshowForm", viewModel);
            }
            if (file != null)
            {
                viewModel.Photo = UploadPhoto(file);
            }
            _slideshowService.Update(Mapper.Map<SlideshowDto>(viewModel));
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int Id)
        {
            _slideshowService.Delete(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        private string UploadPhoto(HttpPostedFileBase file)
        {
            string fileName = "";
            fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid() +
            Path.GetExtension(file.FileName);
            file.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
            return fileName;
        }
    }
}

ProductsCatalog.Website/Controllers/WishListController.cs
using Microsoft.AspNet.Identity;
using ProductsCatalog.Business.DTOs;
using ProductsCatalog.Business.IService;
using ProductsCatalog.Website.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductsCatalog.Website.Controllers
{
    public class WishListController : Controller
    {
        readonly private IWishListService _wishListService;

        public WishListController(IWishListService wishListService)
        {
            _wishListService = wishListService;
        }

        // GET: WishList
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var wishlist = AutoMapper.Mapper.Map<List<WishListViewModel>>(_wishListService.GetAll(userId));
            return View(wishlist);
        }

        [HttpPost]
        public JsonResult AddToWishList(int productId)
        {
            var userId = User.Identity.GetUserId();
            _wishListService.Add(AutoMapper.Mapper.Map<WishListDto>(new { userId = userId, productId = productId, productName = "", productPrice = 0, productPhoto = "" }));
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

ProductsCatalog.Website/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Product Catalog</title>
  <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
  <link href="~/Content/css/prettyPhoto.css" rel="stylesheet">
  <link href="~/Content/css/price-range.css" rel="stylesheet">
  <link href="~/Content/css/animate.css" rel="stylesheet">
  <link href="~/Content/css/main.css" rel="stylesheet">
  <link href="~/Content/css/responsive.css" rel="stylesheet">
  <!--[if lt IE 9]>
  <script src="~/Content/js/html5shiv.js"></script>
  <script src="~/Content/js/respond.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="~/Content/images/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/images/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/images/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/images/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="~/Content/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->
<body>

  @Html.Partial("_NavBar")

  @RenderBody()

  <script src="~/Content/js/jquery.js"></script>
  <script src="~/Content/js/price-range.js"></script>
  <script src="~/Content/js/jquery.scrollUp.min.js"></script>
  <script src="~/Content/js/bootstrap.min.js"></script>
  <script src="~/Content/js/jquery.prettyPhoto.js"></script>
  <script src="~/Content/js/main.js"></script>
</body>
</html>

ProductsCatalog.Website/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Product Catalog</title>
  <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
  <link href="~/Content/css/prettyPhoto.css" rel="stylesheet">
  <link href="~/Content/css/price-range.css" rel="stylesheet">
  <link href="~/Content/css/animate.css" rel="stylesheet">
  <link href="~/Content/css/main.css" rel="stylesheet">
  <link href="~/Content/css/responsive.css" rel="stylesheet">


  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <link rel="shortcut icon" href="~/Content/images/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/images/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/images/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/images/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="~/Content/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->
<body>

  @Html.Partial("_NavBar")

  @if (ViewContext.RouteData.Values["action"] == "Index")
  {
    Html.RenderAction("Slideshow", "Home");
  }
  <section>
    <div class="container">
      <div class="row">
        @{Html.RenderAction("ShowLeftSideMenu", "Home");}
        @RenderBody()
      </div>
    </div>
  </section>

  <script src="~/Content/js/jquery.js"></script>
  <script src="~/Content/js/bootstrap.min.js"></script>
  <script src="~/Content/js/jquery.scrollUp.min.js"></script>
  <script src="~/Content/js/price-range.js"></script>
  <script src="~/Content/js/jquery.prettyPhoto.js"></script>
  <script src="~/Content/js/main.js"></script>
</body>

</html>

ProductsCatalog.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - My ASP.NET Application</title>
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        @*@Html.ActionLink("Products Catalog", "Index", "Category", new { area = "" }, new { @class = "navbar-brand" })*@


      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>@Html.ActionLink("Slideshow", "Index", "Slideshow")</li>
          <li>@Html.ActionLink("Categories", "Index", "Category")</li>
          <li>@Html.ActionLink("Products ", "Index", "Product")</li>
          <li>@Html.ActionLink("Orders ", "Index", "Product")</li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>@Html.ActionLink("Log Out", "LogOut", "Account")</li>
        </ul>

      </div>
    </div>
  </div>
  <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", required: false)
</body>
</html>

ProductsCatalog.Website/Views/Shared/_LeftSideNavBar.cshtml
@model IEnumerable<ProductsCatalog.Website.ViewModels.CategoryViewModel>

<div class="col-sm-3">
  <div class="left-sidebar">
    <h2>Category</h2>
    <div class="panel-group category-products" id="accordian">
      <!--category-productsr-->
      @foreach (var category in Model)
      {
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"><a href="@Url.Action("ViewProducts","Home",new {categoryId= @category.Id})">@category.Name</a></h4>
          </div>
        </div>
      }
    </div><!--/category-products-->
  </div>
</div>

ProductsCatalog.Website/Views/Shared/_NavBar.cshtml
<header id="header">
  <div class="header-middle">
    <!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
          @*  <a href='@Url.Action("Index","Home")'><img src="~/Content/images/home/logo.png" style="width:50%" alt="" /></a>*@
          </div>
        </div>

        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              @if (User.Identity.IsAuthenticated)
              {
                <li style="margin-top: 3%;">Welcome, @User.Identity.Name</li>
                if (User.IsInRole("Admin"))
                {
                  <li><a href='@Url.Action("Index", "Slideshow")'><i class="fa fa-crosshairs"></i> Dashboard</a></li>
                }
                else
                {
                  <li><a href='@Url.Action("Index", "WishList")'><i class="fa fa-star"></i> Wishlist</a></li>
                  @*
                    <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                  *@
                }
                <li><a href='@Url.Action("LogOut", "Account")'><i class="fa fa-user"></i> Log out</a></li>
              }
              else
              {
                <li><a href='@Url.Action("Login", "Account")'><i class="fa fa-lock"></i> Login</a></li>
              }
            </ul>
          </div>
        </div>

      </div>
    </div>
  </div><!--/header-middle-->
</header><!--/header-->

ProductsCatalog.Website/Views/Shared/_Slideshow.cshtml
@model IEnumerable<ProductsCatalog.Website.ViewModels.SlideshowViewModel>

<section id="slider">
  <!--slider-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div id="slider-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">

            @foreach (var slide in Model)
            {
              string className = "";
              if (Model.First() == slide)
              {
                className = "active";
              }
              <li data-target="#slider-carousel" data-slide-to="@slide.Id" class="@className"></li>
            }

          </ol>

          <div class="carousel-inner">

            @foreach (var slide in Model)
            {
              string className = "item";
              if (Model.First() == slide)
              {
                className = "item active";
              }
              <div class="@className">
                <div class="col-sm-6">
                  <h1>@slide.Title</h1>
                  <h2>@slide.SubTitle</h2>
                  <p>@slide.Description</p>
                </div>
                <div class="col-sm-6">
                  <img src="/Uploads/@slide.Photo" class="girl img-responsive" alt="" />
                </div>
              </div>
            }
          </div>
          <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
            <i class="fa fa-angle-left"></i>
          </a>
          <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
            <i class="fa fa-angle-right"></i>
          </a>
        </div>

      </div>
    </div>
  </div>
</section>